### ISSUE TITLE
[FEAT] iOS 3차 과제

### ISSUE THREAD

**Issue by heerucan** [29th-WE-SOPT-iOS-Part/KimRuHee#10]
## 📌  Feature Issue
3차 과제 : 유튜브 홈 화면 구성하기 a.k.a 클코

## 📝  To-do

- [x] 전반적인 UI 레이아웃 잡기
- [x] 하단 세로 스크롤 TableViewCell 파일로 만들기
- [x] 상단 가로 스크롤 CollectionViewCell 자유롭게 만들기
- [x] 도전과제 : text 길이에 따른 cell 크기 구현
- [ ] 스크롤 애니메이션 할 수 있다면 해라^^;
- [x] 에셋 추가
