### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by heerucan** [29th-WE-SOPT-iOS-Part/KimRuHee#12]
## 📌  Feature Issue
4차 서버 통신 과제입니다~

## 📝  To-do

- [x] 시작 스보 변경
- [x] 상단 프로필 선택 시 로그아웃 기능 (로그인 화면으로 이동)
- [x] 로그인 서버 연결
- [x] 회원가입 서버 연결
- [x] 로그인 시 message alert controller
- [x] 회원가입 시 message alert controller
- [ ] (도전과제) user defaults name값 저장하고 이걸 로그인 성공 화면에 띄우기
