### ISSUE TITLE
[FEAT] iOS 1차 과제

### ISSUE THREAD

**Issue by heerucan** [29th-WE-SOPT-iOS-Part/KimRuHee#2]
## 📌 Feature Issue

1주차 과제는 로그인, 회원가입, 확인화면 
UI 구성과 화면전환 그리고 데이터 전달입니다!

## 📝 To-do

▶️ UI 구성하기
- [ ]  로그인 화면 UI 구성하기
- [ ]  회원가입 화면 UI 구성하기
- [ ]  확인 화면 UI 구성하기

▶️ 화면 전환하기
- [ ]  로그인 화면 → 회원가입 화면 으로 push로 화면전환하기
- [ ]  로그인 화면 → 확인 화면 으로 present로 화면전환하기
- [ ]  회원가입 화면 → 확인 화면 으로 present로 화면전환하기

▶️ 기능 구현하기
- [ ]  로그인 화면에서 적은 이름을 확인 화면에서 띄우기
- [ ]  회원가입 화면에서 적은 이름을 확인 화면에서 띄우기

🔥도전과제
- [ ]  로그인화면과 회원가입 화면에서 3개의 textfield값이 모두 채워지면 다음 버튼이 활성화되는 로직 구현하기
- [ ]  회원가입 화면에서 비밀번호 표시를 누를 경우 비밀번호가 표시되도록 구현하기
