### ISSUE TITLE
[FEAT] iOS 2차 과제

### ISSUE THREAD

**Issue by heerucan** [29th-WE-SOPT-iOS-Part/KimRuHee#6]
## 📌 Feature Issue

2주차 과제는 1주차 과제에서 만든 뷰에 AutoLayout을 적용시키는 것과 

Tabbar를 만든 후 확인화면에서 텝바 화면으로 이동하는 것입니다!

## 📝 To-do

▶️ UI 구성하기

- [x]  로그인 화면 AutoLayout 적용하기
- [x]  회원가입 화면 AutoLayout 적용하기
- [x]  확인 화면 AutoLayout 적용하기
- [x]  확인 화면에 "다른 계정으로 로그인하기" 버튼 추가하기

▶️ 화면 전환하기

- [x]  확인 화면에 "다른 계정으로 로그인하기 버튼 추가" 누르면 처음 로그인 화면으로 돌아가기
    - 로그인 → 확인 화면으로 온 경우, 로그인 → 회원가입 → 확인 화면으로 온 경우 모두 동일하게
    버튼을 누르면 처음 로그인 화면으로 돌아가도록 구현하기
- [x]  확인 화면에서 확인 화면 누르면 Tabbar로 연결된 화면 Present 하기

▶️ 기능 구현하기

- [x]  Tabbar에 5개의 view controller 연결하기
- [x]  tabbar title, image, selected image 바꾸기
